# Space saving settings.
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
QMK_SETTINGS = yes
SPACE_CADET_ENABLE = no
KEY_OVERRIDE_ENABLE = no
RGB_MATRIX_ENABLE = yes

VIA_ENABLE = no
VIAL_ENABLE = no
VIALRGB_ENABLE = no
