// Copyright 2023 Conor Burns (@Conor-Burns)
/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once
//#define USB_SUSPEND_WAKEUP_DELAY 10000
//#undef NO_DEBUG
//#define NO_DEBUG
//#undef SPLIT_USB_DETECT
#define RGBLED_NUM 12
#define RGBLED_SPLIT { 6, 6 }
//#define RGBLIGHT_LAYERS
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_MODE_RAINBOW_SWIRL1
//#define SPLIT_USB_TIMEOUT 2000
//#define SPLIT_USB_TIMEOUT_POLL 10
//#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_MOOD
//#define RGBLIGHT_DEFAULT_MODE RGB_MODE_BREATHING
#define WS2812_BYTE_ORDER WS2812_BYTE_ORDER_GRB

