// Copyright 2023 Conor Burns (@Conor-Burns)
/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once
//#define RGBLED_NUM 12
//#define RGB_MATRIX_LED_COUNT 12
#define RGBLIGHT_LED_COUNT 12
#define RGBLED_SPLIT { 6, 6 }
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_MODE_RAINBOW_MOOD0
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_MODE_RAINBOW_SWIRL1
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_MODE_TWINKLE
#define RGBLIGHT_MODE_CHRISTMAS
#define RGBLIGHT_EFFECT_KNIGHT0
#define WS2812_BYTE_ORDER WS2812_BYTE_ORDER_GRB
#define RGBLIGHT_LED_COUNT 12
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
//#define RGBLIGHT_ENABLED
#define RGBLIGHT_LAYERS
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_WATCHDOG_ENABLE
#undef SPLIT_USB_DETECT
